-- AlterTable
ALTER TABLE "users" ADD COLUMN "phone" VARCHAR(20);

ALTER TABLE "users" ADD CONSTRAINT "users_phone_format_check"
CHECK ("phone" IS NULL OR "phone" ~ '^(\+84|0)[0-9]{9,10}$');

-- CreateTable
CREATE TABLE "customer_addresses" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "label" VARCHAR(40) NOT NULL,
    "recipient_name" VARCHAR(100) NOT NULL,
    "phone" VARCHAR(20) NOT NULL,
    "address_line" VARCHAR(250) NOT NULL,
    "ward" VARCHAR(120),
    "district" VARCHAR(120) NOT NULL,
    "province" VARCHAR(120) NOT NULL,
    "is_default" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "customer_addresses_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "customer_addresses_label_not_blank_check" CHECK (length(btrim("label")) > 0),
    CONSTRAINT "customer_addresses_recipient_not_blank_check" CHECK (length(btrim("recipient_name")) > 0),
    CONSTRAINT "customer_addresses_phone_format_check" CHECK ("phone" ~ '^(\+84|0)[0-9]{9,10}$'),
    CONSTRAINT "customer_addresses_address_not_blank_check" CHECK (
        length(btrim("address_line")) > 0
        AND length(btrim("district")) > 0
        AND length(btrim("province")) > 0
    )
);

-- CreateIndex
CREATE INDEX "customer_addresses_user_id_created_at_idx"
ON "customer_addresses"("user_id", "created_at");

-- Một khách chỉ có tối đa một địa chỉ mặc định. Đây là partial unique index
-- (chỉ mục duy nhất có điều kiện), nên được khai báo trực tiếp trong migration.
CREATE UNIQUE INDEX "customer_addresses_one_default_per_user_idx"
ON "customer_addresses"("user_id")
WHERE "is_default" = true;

-- Cursor danh sách đơn dùng id giảm dần trong phạm vi một khách.
CREATE INDEX "orders_user_id_id_idx" ON "orders"("user_id", "id");

-- AddForeignKey
ALTER TABLE "customer_addresses" ADD CONSTRAINT "customer_addresses_user_id_fkey"
FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
