import {
  Difficulty,
  MeasurementUnit,
  RecipeCategory,
  RecipeYieldUnit,
} from '../src/generated/prisma/client.js';

export type RecipeSeedIngredient = {
  slug: string;
  name: string;
  unit: MeasurementUnit;
  quantity: number;
  note?: string;
};

export type RecipeSeedTool = {
  slug: string;
  name: string;
  required?: boolean;
};

export type RecipeSeedDefinition = {
  slug: string;
  title: string;
  imageUrl: string;
  category: RecipeCategory;
  baseServings: number;
  yieldUnit: RecipeYieldUnit;
  prepMinutes: number;
  bakeMinutes: number;
  difficulty: Difficulty;
  sourceYield: string;
  sourceTime: string;
  ingredients: RecipeSeedIngredient[];
  tools: RecipeSeedTool[];
};

const gram = MeasurementUnit.GRAM;
const milliliter = MeasurementUnit.MILLILITER;
const piece = MeasurementUnit.PIECE;

export const importedRecipeSeeds: RecipeSeedDefinition[] = [
  {
    slug: 'cookie-socola',
    title: 'Bánh quy Chocolate Chip',
    imageUrl: '/images/recipes/thumbnails/chocolate-chip-cookies.png',
    category: RecipeCategory.COOKIE,
    baseServings: 30,
    yieldUnit: RecipeYieldUnit.PIECE,
    prepMinutes: 15,
    bakeMinutes: 15,
    difficulty: Difficulty.EASY,
    sourceYield: '25–30 cái',
    sourceTime: 'Chuẩn bị 10–15 phút, nướng 12–15 phút',
    ingredients: [
      { slug: 'bot-mi', name: 'Bột mì đa dụng', unit: gram, quantity: 150 },
      { slug: 'bo-lat', name: 'Bơ lạt', unit: gram, quantity: 165 },
      { slug: 'duong-cat', name: 'Đường trắng', unit: gram, quantity: 80 },
      { slug: 'duong-nau', name: 'Đường nâu', unit: gram, quantity: 80 },
      { slug: 'trung-ga', name: 'Trứng gà', unit: piece, quantity: 2 },
      { slug: 'vani-chiet-xuat', name: 'Vani chiết xuất', unit: milliliter, quantity: 10 },
      { slug: 'muoi-no', name: 'Muối nở (baking soda)', unit: gram, quantity: 3, note: 'Tài liệu ghi 2–3 g; dữ liệu tạm lấy cận trên để tránh thiếu.' },
      { slug: 'muoi', name: 'Muối ăn', unit: gram, quantity: 2, note: 'Tài liệu ghi 1–2 g; dữ liệu tạm lấy cận trên để tránh thiếu.' },
      { slug: 'socola-chip', name: 'Sô-cô-la chip', unit: gram, quantity: 130, note: 'Tài liệu ghi 100–130 g; dữ liệu tạm lấy cận trên để tránh thiếu.' },
    ],
    tools: [
      { slug: 'to-tron', name: 'Tô trộn' },
      { slug: 'phoi-long', name: 'Phới lồng' },
      { slug: 'spatula', name: 'Spatula' },
      { slug: 'can-dien-tu', name: 'Cân điện tử' },
      { slug: 'khay-nuong', name: 'Khay nướng' },
      { slug: 'giay-nen', name: 'Giấy nến' },
      { slug: 'lo-nuong', name: 'Lò nướng' },
    ],
  },
  {
    slug: 'banh-quy-bo-tra-xanh',
    title: 'Bánh quy bơ vị trà xanh',
    imageUrl: '/images/recipes/thumbnails/matcha-meltaways-cookies.png',
    category: RecipeCategory.COOKIE,
    baseServings: 32,
    yieldUnit: RecipeYieldUnit.PIECE,
    prepMinutes: 15,
    bakeMinutes: 30,
    difficulty: Difficulty.MEDIUM,
    sourceYield: '30–32 cái',
    sourceTime: 'Chuẩn bị 10–15 phút, nướng 30 phút',
    ingredients: [
      { slug: 'bot-mi', name: 'Bột mì đa dụng', unit: gram, quantity: 140 },
      { slug: 'bo-lat', name: 'Bơ lạt', unit: gram, quantity: 160 },
      { slug: 'bot-ngo', name: 'Bột ngô', unit: gram, quantity: 30 },
      { slug: 'bot-tra-xanh', name: 'Bột trà xanh', unit: gram, quantity: 15, note: 'Tài liệu ghi 10–15 g; dữ liệu tạm lấy cận trên để tránh thiếu.' },
      { slug: 'duong-cat', name: 'Đường trắng', unit: gram, quantity: 100 },
      { slug: 'trung-ga', name: 'Trứng gà', unit: piece, quantity: 1 },
      { slug: 'vani-chiet-xuat', name: 'Vani chiết xuất', unit: milliliter, quantity: 3 },
    ],
    tools: [
      { slug: 'to-tron', name: 'Tô trộn' },
      { slug: 'phoi-long', name: 'Phới lồng' },
      { slug: 'spatula', name: 'Spatula' },
      { slug: 'can-dien-tu', name: 'Cân điện tử' },
      { slug: 'khay-nuong', name: 'Khay nướng' },
      { slug: 'giay-nen', name: 'Giấy nến' },
      { slug: 'lo-nuong', name: 'Lò nướng' },
      { slug: 'dui-wilton-1m', name: 'Đui bắt kem Wilton 1M' },
      { slug: 'tui-bat-kem', name: 'Túi bắt bông kem' },
      { slug: 'may-danh-trung-cam-tay', name: 'Máy đánh trứng cầm tay' },
    ],
  },
  {
    slug: 'banh-quy-bo-cranberry',
    title: 'Bánh quy bơ nhân cranberry',
    imageUrl: '/images/recipes/thumbnails/cranberry-butter-cookies.png',
    category: RecipeCategory.COOKIE,
    baseServings: 30,
    yieldUnit: RecipeYieldUnit.PIECE,
    prepMinutes: 20,
    bakeMinutes: 15,
    difficulty: Difficulty.MEDIUM,
    sourceYield: '25–30 cái',
    sourceTime: 'Chuẩn bị 15–20 phút, nướng 12–15 phút',
    ingredients: [
      { slug: 'bot-mi', name: 'Bột mì đa dụng', unit: gram, quantity: 240 },
      { slug: 'bo-lat', name: 'Bơ lạt', unit: gram, quantity: 225 },
      { slug: 'duong-hat-min', name: 'Đường hạt mịn', unit: gram, quantity: 135 },
      { slug: 'muoi', name: 'Muối ăn', unit: gram, quantity: 2 },
      { slug: 'vani-chiet-xuat', name: 'Vani chiết xuất', unit: milliliter, quantity: 5 },
      { slug: 'trung-ga', name: 'Trứng gà', unit: piece, quantity: 1 },
    ],
    tools: [
      { slug: 'can-dien-tu', name: 'Cân điện tử' },
      { slug: 'to-tron', name: 'Tô trộn' },
      { slug: 'may-danh-trung', name: 'Máy đánh trứng' },
      { slug: 'khay-nuong', name: 'Khay nướng' },
      { slug: 'giay-nen', name: 'Giấy nến' },
      { slug: 'phoi-long', name: 'Phới lồng' },
      { slug: 'tui-bat-kem', name: 'Túi bắt kem' },
      { slug: 'dui-bat-kem', name: 'Đui bắt kem' },
    ],
  },
  {
    slug: 'cheesecake-khong-nuong',
    title: 'Cheesecake không nướng',
    imageUrl: '/images/recipes/thumbnails/no-bake-cheesecake.png',
    category: RecipeCategory.CAKE,
    baseServings: 10,
    yieldUnit: RecipeYieldUnit.PORTION,
    prepMinutes: 120,
    bakeMinutes: 0,
    difficulty: Difficulty.HARD,
    sourceYield: '8–10 phần',
    sourceTime: 'Chuẩn bị 110–120 phút, chờ đông 6–8 giờ',
    ingredients: [
      { slug: 'banh-quy', name: 'Bánh quy', unit: gram, quantity: 200, note: 'Phần đế bánh.' },
      { slug: 'bo-lat', name: 'Bơ lạt', unit: gram, quantity: 100, note: 'Phần đế bánh.' },
      { slug: 'duong-cat', name: 'Đường trắng', unit: gram, quantity: 120, note: '20 g cho đế và 100 g cho nhân.' },
      { slug: 'cream-cheese', name: 'Kem phô mai', unit: gram, quantity: 250, note: 'Phần nhân bánh.' },
      { slug: 'kem-tuoi', name: 'Kem tươi (whipping cream)', unit: milliliter, quantity: 200, note: 'Hàm lượng béo 30–40%.' },
      { slug: 'vani-chiet-xuat', name: 'Vani chiết xuất', unit: milliliter, quantity: 5 },
      { slug: 'gelatin-la', name: 'Gelatin lá', unit: piece, quantity: 3 },
    ],
    tools: [
      { slug: 'khuon-tron-18-20', name: 'Khuôn tròn 18–20 cm' },
      { slug: 'may-danh-trung', name: 'Máy đánh trứng' },
      { slug: 'to-tron', name: 'Tô trộn' },
      { slug: 'spatula', name: 'Spatula' },
      { slug: 'giay-nen', name: 'Giấy nến' },
    ],
  },
  {
    slug: 'red-velvet-cake',
    title: 'Red Velvet Cake',
    imageUrl: '/images/recipes/thumbnails/red-velvet-cake.png',
    category: RecipeCategory.CAKE,
    baseServings: 8,
    yieldUnit: RecipeYieldUnit.PORTION,
    prepMinutes: 40,
    bakeMinutes: 30,
    difficulty: Difficulty.HARD,
    sourceYield: '8 phần',
    sourceTime: 'Chuẩn bị 40 phút, nướng 25–30 phút',
    ingredients: [
      { slug: 'sua-tuoi', name: 'Sữa tươi không đường', unit: milliliter, quantity: 240 },
      { slug: 'dam-trang', name: 'Dấm trắng hoặc nước cốt chanh', unit: milliliter, quantity: 20, note: '15 ml pha sữa và 5 ml kích hoạt muối nở.' },
      { slug: 'bot-mi', name: 'Bột mì đa dụng', unit: gram, quantity: 240 },
      { slug: 'bot-no', name: 'Bột nở (baking powder)', unit: gram, quantity: 5 },
      { slug: 'bot-cacao', name: 'Bột cacao nguyên chất không đường', unit: gram, quantity: 20 },
      { slug: 'bo-lat', name: 'Bơ lạt', unit: gram, quantity: 120 },
      { slug: 'duong-cat', name: 'Đường trắng', unit: gram, quantity: 170 },
      { slug: 'trung-ga', name: 'Trứng gà', unit: piece, quantity: 2 },
      { slug: 'vani-chiet-xuat', name: 'Vani chiết xuất', unit: milliliter, quantity: 10, note: '5 ml cho cốt và 5 ml cho kem.' },
      { slug: 'mau-thuc-pham-do', name: 'Màu thực phẩm đỏ', unit: milliliter, quantity: 30 },
      { slug: 'muoi-no', name: 'Muối nở (baking soda)', unit: gram, quantity: 5 },
      { slug: 'cream-cheese', name: 'Kem phô mai', unit: gram, quantity: 250 },
      { slug: 'kem-tuoi', name: 'Kem tươi (whipping cream)', unit: milliliter, quantity: 200 },
      { slug: 'duong-hat-min', name: 'Đường hạt mịn', unit: gram, quantity: 70 },
      { slug: 'mascarpone', name: 'Mascarpone', unit: gram, quantity: 150 },
    ],
    tools: [
      { slug: 'khuon-tron-20-22', name: 'Khuôn tròn 20–22 cm' },
      { slug: 'giay-nen', name: 'Giấy nến' },
      { slug: 'lo-nuong', name: 'Lò nướng' },
      { slug: 'spatula', name: 'Spatula' },
      { slug: 'phoi-long', name: 'Phới lồng' },
      { slug: 'to-tron', name: 'Tô trộn' },
      { slug: 'may-danh-trung', name: 'Máy đánh trứng' },
    ],
  },
  {
    slug: 'sponge-cake-3-trung',
    title: 'Bánh bông lan 3 trứng',
    imageUrl: '/images/recipes/thumbnails/sponge-cake.png',
    category: RecipeCategory.CAKE,
    baseServings: 6,
    yieldUnit: RecipeYieldUnit.PORTION,
    prepMinutes: 25,
    bakeMinutes: 35,
    difficulty: Difficulty.MEDIUM,
    sourceYield: '6 phần, khuôn 15–18 cm',
    sourceTime: 'Chuẩn bị 20–25 phút, nướng 25–35 phút',
    ingredients: [
      { slug: 'bot-mi', name: 'Bột mì đa dụng', unit: gram, quantity: 30 },
      { slug: 'bot-ngo', name: 'Bột ngô', unit: gram, quantity: 30 },
      { slug: 'dau-an', name: 'Dầu ăn', unit: gram, quantity: 20 },
      { slug: 'sua-tuoi-theo-khoi-luong', name: 'Sữa tươi không đường (theo khối lượng)', unit: gram, quantity: 10 },
      { slug: 'trung-ga', name: 'Trứng gà', unit: piece, quantity: 3 },
      { slug: 'duong-cat', name: 'Đường trắng', unit: gram, quantity: 60 },
      { slug: 'cream-of-tartar', name: 'Cream of tartar', unit: gram, quantity: 2.5 },
      { slug: 'muoi', name: 'Muối ăn', unit: gram, quantity: 0.5 },
    ],
    tools: [
      { slug: 'khuon-tron-15-18', name: 'Khuôn tròn 15–18 cm' },
      { slug: 'giay-nen', name: 'Giấy nến' },
      { slug: 'lo-nuong', name: 'Lò nướng' },
      { slug: 'phoi-long', name: 'Phới lồng' },
      { slug: 'to-tron', name: 'Tô trộn' },
      { slug: 'may-danh-trung', name: 'Máy đánh trứng' },
      { slug: 'ray', name: 'Rây' },
    ],
  },
  {
    slug: 'sponge-cake-4-trung',
    title: 'Bánh bông lan 4 trứng',
    imageUrl: '/images/recipes/thumbnails/sponge-cake.png',
    category: RecipeCategory.CAKE,
    baseServings: 8,
    yieldUnit: RecipeYieldUnit.PORTION,
    prepMinutes: 25,
    bakeMinutes: 35,
    difficulty: Difficulty.MEDIUM,
    sourceYield: '8 phần, khuôn 18–21 cm',
    sourceTime: 'Chuẩn bị 20–25 phút, nướng 25–35 phút',
    ingredients: [
      { slug: 'bot-mi', name: 'Bột mì đa dụng', unit: gram, quantity: 40 },
      { slug: 'bot-ngo', name: 'Bột ngô', unit: gram, quantity: 40 },
      { slug: 'dau-an', name: 'Dầu ăn', unit: gram, quantity: 30 },
      { slug: 'sua-tuoi-theo-khoi-luong', name: 'Sữa tươi không đường (theo khối lượng)', unit: gram, quantity: 15 },
      { slug: 'trung-ga', name: 'Trứng gà', unit: piece, quantity: 4 },
      { slug: 'duong-cat', name: 'Đường trắng', unit: gram, quantity: 80 },
      { slug: 'cream-of-tartar', name: 'Cream of tartar', unit: gram, quantity: 2.5 },
      { slug: 'muoi', name: 'Muối ăn', unit: gram, quantity: 0.5 },
    ],
    tools: [
      { slug: 'khuon-tron-18-21', name: 'Khuôn tròn 18–21 cm' },
      { slug: 'giay-nen', name: 'Giấy nến' },
      { slug: 'lo-nuong', name: 'Lò nướng' },
      { slug: 'phoi-long', name: 'Phới lồng' },
      { slug: 'to-tron', name: 'Tô trộn' },
      { slug: 'may-danh-trung', name: 'Máy đánh trứng' },
      { slug: 'ray', name: 'Rây' },
    ],
  },
  {
    slug: 'tiramisu',
    title: 'Tiramisu',
    imageUrl: '/images/recipes/thumbnails/tiramisu.png',
    category: RecipeCategory.DESSERT,
    baseServings: 8,
    yieldUnit: RecipeYieldUnit.PORTION,
    prepMinutes: 30,
    bakeMinutes: 0,
    difficulty: Difficulty.EASY,
    sourceYield: '6–8 phần',
    sourceTime: 'Chuẩn bị 30 phút',
    ingredients: [
      { slug: 'trung-ga', name: 'Trứng gà', unit: piece, quantity: 2 },
      { slug: 'duong-cat', name: 'Đường trắng', unit: gram, quantity: 50 },
      { slug: 'kem-tuoi', name: 'Kem tươi (whipping cream)', unit: milliliter, quantity: 200, note: 'Hàm lượng béo 30–40%.' },
      { slug: 'bot-sua-beo', name: 'Bột sữa béo', unit: gram, quantity: 10 },
      { slug: 'sua-tuoi', name: 'Sữa tươi không đường', unit: milliliter, quantity: 30 },
      { slug: 'ca-phe-goi', name: 'Cà phê gói', unit: piece, quantity: 2 },
      { slug: 'ruou-rum', name: 'Rượu rum', unit: milliliter, quantity: 20 },
      { slug: 'cream-cheese', name: 'Kem phô mai', unit: gram, quantity: 200 },
      { slug: 'banh-sampa', name: 'Bánh sampa', unit: piece, quantity: 1, note: 'Tài liệu ghi 1 túi; đơn vị túi đang được biểu diễn tạm bằng 1 cái.' },
    ],
    tools: [
      { slug: 'spatula', name: 'Spatula' },
      { slug: 'to-tron', name: 'Tô trộn' },
      { slug: 'ray', name: 'Rây' },
      { slug: 'phoi-long', name: 'Phới lồng' },
      { slug: 'tui-bat-kem', name: 'Túi bắt kem' },
    ],
  },
  {
    slug: 'flan-caramel',
    title: 'Flan Caramel',
    imageUrl: '/images/recipes/thumbnails/flan-caramel.png',
    category: RecipeCategory.DESSERT,
    baseServings: 10,
    yieldUnit: RecipeYieldUnit.PIECE,
    prepMinutes: 15,
    bakeMinutes: 35,
    difficulty: Difficulty.EASY,
    sourceYield: '8–10 cốc',
    sourceTime: 'Chuẩn bị 15 phút, nướng 25–35 phút',
    ingredients: [
      { slug: 'trung-ga', name: 'Trứng gà', unit: piece, quantity: 5 },
      { slug: 'duong-cat', name: 'Đường trắng', unit: gram, quantity: 140, note: '70 g cho flan và 70 g cho caramel.' },
      { slug: 'sua-tuoi', name: 'Sữa tươi không đường', unit: milliliter, quantity: 400 },
      { slug: 'kem-tuoi', name: 'Kem tươi (whipping cream)', unit: milliliter, quantity: 150 },
      { slug: 'vani-chiet-xuat', name: 'Vani chiết xuất', unit: milliliter, quantity: 5 },
      { slug: 'nuoc-cot-chanh', name: 'Nước cốt chanh', unit: milliliter, quantity: 5 },
    ],
    tools: [
      { slug: 'ramekin-su', name: 'Cốc ramekin sứ' },
      { slug: 'to-tron', name: 'Tô trộn' },
      { slug: 'phoi-long', name: 'Phới lồng' },
      { slug: 'ray', name: 'Rây' },
      { slug: 'khay-nuong', name: 'Khay nướng' },
      { slug: 'lo-nuong', name: 'Lò nướng' },
    ],
  },
  {
    slug: 'mousse-socola-dau-tay',
    title: 'Mousse sô-cô-la và dâu tây',
    imageUrl: '/images/recipes/thumbnails/chocolate-strawberry-mousse.png',
    category: RecipeCategory.DESSERT,
    baseServings: 4,
    yieldUnit: RecipeYieldUnit.PORTION,
    prepMinutes: 50,
    bakeMinutes: 0,
    difficulty: Difficulty.MEDIUM,
    sourceYield: '4 phần',
    sourceTime: 'Chuẩn bị 50 phút',
    ingredients: [
      { slug: 'socola-den', name: 'Sô-cô-la đen', unit: gram, quantity: 80 },
      { slug: 'sua-tuoi', name: 'Sữa tươi không đường', unit: milliliter, quantity: 30 },
      { slug: 'trung-ga', name: 'Trứng gà', unit: piece, quantity: 1 },
      { slug: 'kem-tuoi', name: 'Kem tươi (whipping cream)', unit: milliliter, quantity: 280, note: '155 ml cho mousse sô-cô-la và 125 ml cho mousse dâu.' },
      { slug: 'muoi', name: 'Muối ăn', unit: gram, quantity: 0.625 },
      { slug: 'duong-cat', name: 'Đường trắng', unit: gram, quantity: 50, note: '10 g cho mousse sô-cô-la và 40 g cho mousse dâu.' },
      { slug: 'gelatin-la', name: 'Gelatin lá', unit: piece, quantity: 5 },
      { slug: 'dau-tay', name: 'Dâu tây', unit: gram, quantity: 200 },
      { slug: 'nuoc-cot-chanh', name: 'Nước cốt chanh', unit: milliliter, quantity: 5 },
    ],
    tools: [
      { slug: 'phoi-long', name: 'Phới lồng' },
      { slug: 'spatula', name: 'Spatula' },
      { slug: 'khuon-tuy-chon', name: 'Khuôn tùy chọn', required: false },
    ],
  },
  {
    slug: 'banh-mi-sua-hokkaido',
    title: 'Bánh mì sữa Hokkaido',
    imageUrl: '/images/recipes/thumbnails/hokkaido-milk-bread.png',
    category: RecipeCategory.BREAD,
    baseServings: 1,
    yieldUnit: RecipeYieldUnit.LOAF,
    prepMinutes: 210,
    bakeMinutes: 0,
    difficulty: Difficulty.HARD,
    sourceYield: '1 ổ lớn hoặc nhiều bánh nhỏ tùy tạo hình',
    sourceTime: 'Chuẩn bị 3–3,5 giờ, gồm thời gian ủ bột',
    ingredients: [
      { slug: 'bot-banh-mi', name: 'Bột làm bánh mì', unit: gram, quantity: 540 },
      { slug: 'bot-banh-ngot', name: 'Bột làm bánh ngọt', unit: gram, quantity: 60 },
      { slug: 'men-instant', name: 'Men instant', unit: gram, quantity: 10 },
      { slug: 'sua-bot', name: 'Sữa bột', unit: gram, quantity: 30 },
      { slug: 'duong-cat', name: 'Đường trắng', unit: gram, quantity: 80 },
      { slug: 'muoi', name: 'Muối ăn', unit: gram, quantity: 8 },
      { slug: 'trung-ga-theo-khoi-luong', name: 'Trứng gà (theo khối lượng)', unit: gram, quantity: 60 },
      { slug: 'sua-tuoi-theo-khoi-luong', name: 'Sữa tươi không đường (theo khối lượng)', unit: gram, quantity: 250 },
      { slug: 'kem-tuoi-theo-khoi-luong', name: 'Kem tươi (theo khối lượng)', unit: gram, quantity: 150 },
    ],
    tools: [
      { slug: 'to-tron', name: 'Tô trộn' },
      { slug: 'dung-cu-tron-bot', name: 'Dụng cụ trộn bột' },
      { slug: 'may-nhoi-bot', name: 'Máy nhồi bột', required: false },
      { slug: 'cay-can-bot', name: 'Cây cán bột' },
      { slug: 'khay-nuong', name: 'Khay nướng' },
      { slug: 'giay-nen', name: 'Giấy nến' },
      { slug: 'lo-nuong', name: 'Lò nướng' },
    ],
  },
  {
    slug: 'croissant',
    title: 'Croissant',
    imageUrl: '/images/recipes/thumbnails/croissant.png',
    category: RecipeCategory.BREAD,
    baseServings: 10,
    yieldUnit: RecipeYieldUnit.PIECE,
    prepMinutes: 180,
    bakeMinutes: 0,
    difficulty: Difficulty.HARD,
    sourceYield: '10 cái nhỏ',
    sourceTime: 'Chuẩn bị 2,5–3 giờ, gồm thời gian ủ bột',
    ingredients: [
      { slug: 'bot-mi', name: 'Bột mì đa dụng', unit: gram, quantity: 200 },
      { slug: 'sua-tuoi-theo-khoi-luong', name: 'Sữa tươi không đường (theo khối lượng)', unit: gram, quantity: 90 },
      { slug: 'nuoc-cot-chanh-theo-khoi-luong', name: 'Nước cốt chanh (theo khối lượng)', unit: gram, quantity: 5 },
      { slug: 'men-instant', name: 'Men instant', unit: gram, quantity: 3 },
      { slug: 'bo-lat', name: 'Bơ lạt', unit: gram, quantity: 35 },
      { slug: 'duong-cat', name: 'Đường trắng', unit: gram, quantity: 25 },
      { slug: 'trung-ga-theo-khoi-luong', name: 'Trứng gà (theo khối lượng)', unit: gram, quantity: 30 },
      { slug: 'muoi', name: 'Muối ăn', unit: gram, quantity: 2 },
    ],
    tools: [
      { slug: 'to-tron', name: 'Tô trộn' },
      { slug: 'dung-cu-tron-bot', name: 'Dụng cụ trộn bột' },
      { slug: 'may-nhoi-bot', name: 'Máy nhồi bột', required: false },
      { slug: 'cay-can-bot', name: 'Cây cán bột' },
      { slug: 'khay-nuong', name: 'Khay nướng' },
      { slug: 'giay-nen', name: 'Giấy nến' },
      { slug: 'lo-nuong', name: 'Lò nướng' },
    ],
  },
  {
    slug: 'papparoti',
    title: 'Papparoti',
    imageUrl: '/images/recipes/thumbnails/papparoti-coffee-bun.png',
    category: RecipeCategory.BREAD,
    baseServings: 12,
    yieldUnit: RecipeYieldUnit.PIECE,
    prepMinutes: 150,
    bakeMinutes: 0,
    difficulty: Difficulty.HARD,
    sourceYield: '12 bánh',
    sourceTime: 'Chuẩn bị 2–2,5 giờ, gồm thời gian ủ bột',
    ingredients: [
      { slug: 'bot-banh-mi', name: 'Bột làm bánh mì', unit: gram, quantity: 260, note: 'Phần vỏ bánh.' },
      { slug: 'bot-mi', name: 'Bột mì đa dụng', unit: gram, quantity: 35, note: 'Phần phủ cà phê.' },
      { slug: 'duong-hat-min', name: 'Đường hạt mịn', unit: gram, quantity: 60, note: '35 g cho vỏ và 25 g cho phần phủ.' },
      { slug: 'muoi', name: 'Muối ăn', unit: gram, quantity: 4, note: '3 g cho vỏ và 1 g cho phần phủ.' },
      { slug: 'men-instant', name: 'Men instant', unit: gram, quantity: 5 },
      { slug: 'sua-tuoi', name: 'Sữa tươi không đường', unit: milliliter, quantity: 120 },
      { slug: 'nuoc-cot-chanh', name: 'Nước cốt chanh', unit: milliliter, quantity: 3 },
      { slug: 'trung-ga', name: 'Trứng gà', unit: piece, quantity: 1.5, note: '1 quả cho vỏ và 1/2 quả cho phần phủ.' },
      { slug: 'bo-lat', name: 'Bơ lạt', unit: gram, quantity: 112, note: '40 g cho vỏ, 30 g cho phần phủ và khoảng 42 g làm nhân.' },
      { slug: 'bot-cacao', name: 'Bột cacao nguyên chất không đường', unit: gram, quantity: 1 },
      { slug: 'ca-phe-dam-dac', name: 'Cà phê đậm đặc', unit: milliliter, quantity: 10 },
    ],
    tools: [
      { slug: 'to-tron', name: 'Tô trộn' },
      { slug: 'dung-cu-tron-bot', name: 'Dụng cụ trộn bột' },
      { slug: 'may-nhoi-bot', name: 'Máy nhồi bột', required: false },
      { slug: 'cay-can-bot', name: 'Cây cán bột' },
      { slug: 'khay-nuong', name: 'Khay nướng' },
      { slug: 'giay-nen', name: 'Giấy nến' },
      { slug: 'lo-nuong', name: 'Lò nướng' },
      { slug: 'ray', name: 'Rây' },
      { slug: 'tui-bat-kem', name: 'Túi bắt kem' },
    ],
  },
];
