-- CreateEnum
CREATE TYPE "OrderStatus" AS ENUM (
    'AWAITING_PAYMENT',
    'CONFIRMED',
    'PAYMENT_REVIEW',
    'PREPARING',
    'SHIPPING',
    'DELIVERED',
    'CANCELLED'
);

-- CreateEnum
CREATE TYPE "PaymentProvider" AS ENUM ('ZALOPAY');

-- CreateEnum
CREATE TYPE "PaymentStatus" AS ENUM (
    'PENDING',
    'SUCCEEDED',
    'FAILED',
    'EXPIRED',
    'CANCELLED',
    'REFUND_PENDING',
    'REFUNDED'
);

-- CreateTable
CREATE TABLE "orders" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "order_number" VARCHAR(24) NOT NULL,
    "idempotency_key" UUID NOT NULL,
    "user_id" BIGINT NOT NULL,
    "status" "OrderStatus" NOT NULL DEFAULT 'AWAITING_PAYMENT',
    "currency" CHAR(3) NOT NULL DEFAULT 'VND',
    "subtotal" DECIMAL(14,2) NOT NULL,
    "shipping_fee" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "total" DECIMAL(14,2) NOT NULL,
    "recipient_name" VARCHAR(100) NOT NULL,
    "recipient_phone" VARCHAR(20) NOT NULL,
    "address_line" VARCHAR(250) NOT NULL,
    "ward" VARCHAR(120),
    "district" VARCHAR(120) NOT NULL,
    "province" VARCHAR(120) NOT NULL,
    "note" VARCHAR(500),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "orders_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "orders_currency_check" CHECK ("currency" = 'VND'),
    CONSTRAINT "orders_amounts_nonnegative_check" CHECK (
        "subtotal" >= 0 AND "shipping_fee" >= 0 AND "total" >= 0
    ),
    CONSTRAINT "orders_total_matches_check" CHECK ("total" = "subtotal" + "shipping_fee")
);

-- CreateTable
CREATE TABLE "order_items" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "order_id" BIGINT NOT NULL,
    "product_variant_id" BIGINT,
    "product_name" VARCHAR(180) NOT NULL,
    "sku" VARCHAR(80) NOT NULL,
    "variant_label" VARCHAR(180) NOT NULL,
    "quantity" SMALLINT NOT NULL,
    "unit_price" DECIMAL(14,2) NOT NULL,
    "line_total" DECIMAL(14,2) NOT NULL,

    CONSTRAINT "order_items_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "order_items_quantity_positive_check" CHECK ("quantity" > 0),
    CONSTRAINT "order_items_amounts_nonnegative_check" CHECK (
        "unit_price" >= 0 AND "line_total" >= 0
    ),
    CONSTRAINT "order_items_total_matches_check" CHECK ("line_total" = "unit_price" * "quantity")
);

-- CreateTable
CREATE TABLE "payments" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "order_id" BIGINT NOT NULL,
    "provider" "PaymentProvider" NOT NULL,
    "status" "PaymentStatus" NOT NULL DEFAULT 'PENDING',
    "amount" DECIMAL(14,2) NOT NULL,
    "merchant_transaction_id" VARCHAR(40) NOT NULL,
    "provider_transaction_id" VARCHAR(50),
    "checkout_url" VARCHAR(2048),
    "provider_token" VARCHAR(512),
    "return_code" INTEGER,
    "return_message" VARCHAR(500),
    "expires_at" TIMESTAMPTZ(3) NOT NULL,
    "paid_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "payments_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "payments_amount_positive_check" CHECK ("amount" > 0)
);

-- CreateIndex
CREATE UNIQUE INDEX "orders_order_number_key" ON "orders"("order_number");

-- CreateIndex
CREATE UNIQUE INDEX "orders_idempotency_key_key" ON "orders"("idempotency_key");

-- CreateIndex
CREATE INDEX "orders_user_id_created_at_idx" ON "orders"("user_id", "created_at");

-- CreateIndex
CREATE INDEX "orders_status_created_at_idx" ON "orders"("status", "created_at");

-- CreateIndex
CREATE INDEX "order_items_order_id_idx" ON "order_items"("order_id");

-- CreateIndex
CREATE INDEX "order_items_product_variant_id_idx" ON "order_items"("product_variant_id");

-- CreateIndex
CREATE UNIQUE INDEX "payments_merchant_transaction_id_key" ON "payments"("merchant_transaction_id");

-- CreateIndex
CREATE INDEX "payments_order_id_created_at_idx" ON "payments"("order_id", "created_at");

-- CreateIndex
CREATE INDEX "payments_status_expires_at_idx" ON "payments"("status", "expires_at");

-- AddForeignKey
ALTER TABLE "orders" ADD CONSTRAINT "orders_user_id_fkey"
FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_order_id_fkey"
FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_product_variant_id_fkey"
FOREIGN KEY ("product_variant_id") REFERENCES "product_variants"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payments" ADD CONSTRAINT "payments_order_id_fkey"
FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE CASCADE;
